development:
  adapter: mysql2
  encoding: utf8
  database: sample_app_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: sample_app_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: postgresql
  encoding: unicode
  database: sample_app_production
  pool: 5
  username: myapp
  password:
